### ISSUE TITLE
Classes not found on the first try

### ISSUE THREAD

**Issue by alex3627** [jiptool/jip#11]
Class loading is not always working on the first try, but on the second.

Example:

Jython 2.5.3 (2.5:c56500f08d34+, Aug 13 2012, 14:48:36) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.7.0_03
Type "help", "copyright", "credits" or "license" for more information.
>>> from jip import embed
>>> embed.require('com.itextpdf:itextpdf:5.3.2')
>>> import com
>>> com.itextpdf.text.Document
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'javapackage' object has no attribute 'itextpdf'
>>> com.itextpdf.text.Document
<type 'com.itextpdf.text.Document'>

**Comment by wikier** [comment]
Closing... Old issue.
