### ISSUE TITLE
jip executable not found

### ISSUE THREAD

**Issue by ghost** [jiptool/jip#12]
Hi,

I am trying to use jython with cucumber-jvm as it is shown in the following site

http://supersabrams.com/blog/?p=386

I need jip for that. I have installed jip as explained there, but I am not able to find the jip executable.

Where should it be?

I need to run this and I really don't know how.

jip install info.cukes:cucumber-jython:1.0.1

Any ideas?

Thanks

M

**Comment by wikier** [comment]
Closing... Old issue.
