### ISSUE TITLE
Add automated PyPI deployment from travis

### ISSUE THREAD

**Issue by baztian** [jiptool/jip#41]
@sunng87, it would be nice if you could follow
https://docs.travis-ci.com/user/deployment/pypi/
to allow for PyPI deployment on tagged commits. This way @wikier and I could publish new releases. I don't think @wikier and I have write access to https://pypi.python.org/pypi/jip
Using travis PyPI deployment would ease the overall release process.

I think it should look something like this:

    ...
    sudo: false
    
    deploy:
      provider: pypi
      user: sunng
      password:
        secure: yourEncryptedPwd
      distributions: "sdist bdist_wheel"
      on:
        tags: true
        repo: jiptool/jip
    
    python:
...

(After you've set this up I might implement a .bumpversion.cfg to use bumpversion to do the tagging, changelog manipulation and the like to further ease the deployment process.)

**Comment by sunng87** [comment]
@baztian I was about to ask your pypi username to add access for you. But this approach is definitely better. Let me do it.

**Comment by sunng87** [comment]
Finished travis setup and released 0.9.11 from there.

**Comment by baztian** [comment]
Wow looks awsome! Thanks. Adding me to pypi would be nice too. This way I can do test deployments to pypitest. My pypi username is cheffe :sunglasses:

**Comment by sunng87** [comment]
Added 👍
