### ISSUE TITLE
PyPI permission error

### ISSUE THREAD

**Issue by baztian** [jiptool/jip#54]
@sunng87 , can you please verify your PyPi Email address? Deploying to PyPI currently fails: https://travis-ci.org/github/jiptool/jip/jobs/690929190#L479
See https://pypi.org/help/#verified-email for more details.

**Comment by baztian** [comment]
I've manually uploaded to https://pypi.org/project/jip/0.9.14/#files as I am a PyPI jip contributor. (Wasn't aware of). @sunng87  and @wikier I've created a test.pypi of the project to test uploading and other pypi stuff: https://test.pypi.org/project/jip/
If you like to get a owner/maintainer of that test project as well please let me know. I think you have to create a separate user at test.pypi.org.

**Comment by sunng87** [comment]
Sorry for late response. I have verified my email.

**Comment by sunng87** [comment]
Thank you @baztian . Since I'm no longer working on any python/jython projects, I won't be active in maintaining this project. Feel free to change anything about jip. But it's welcomed to ping me if you need any help.

**Comment by baztian** [comment]
Thanks @sunng87 !
